// Code generated by abi-manifest-gen; DO NOT EDIT.
// clang-format off
#ifndef SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_GENERATED_H
#define SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SURGE_TYPED_CARRIER_ABI_VERSION UINT32_C(2)
#define SURGE_TYPED_CARRIER_ABI_MANIFEST_HASH "5c95dc2f8fe5939fcd21ee528515403a3b5bc8c083fd002e3b40f968b9b389e6"
#define SURGE_TYPED_CARRIER_ABI_SENTINEL __surge_runtime_abi_typed_carrier_v2_5c95dc2f8fe5939fcd21ee528515403a3b5bc8c083fd002e3b40f968b9b389e6

typedef uint64_t rt_value_flags;
#define RT_VALUE_FLAG_COPY UINT64_C(1)
#define RT_VALUE_FLAG_CLONABLE UINT64_C(2)
#define RT_VALUE_FLAG_DROPPABLE UINT64_C(4)
#define RT_VALUE_FLAG_TRACEABLE UINT64_C(8)
#define RT_VALUE_FLAG_SHARD_MOVABLE UINT64_C(16)
#define RT_VALUE_FLAG_CROSS_CLONABLE UINT64_C(32)

typedef uint32_t rt_carrier_status;
#define RT_CARRIER_STATUS_OK UINT32_C(0)
#define RT_CARRIER_STATUS_OVERFLOW UINT32_C(1)
#define RT_CARRIER_STATUS_CAPACITY UINT32_C(2)
#define RT_CARRIER_STATUS_STALE_GENERATION UINT32_C(3)
#define RT_CARRIER_STATUS_PUBLICATION_REJECTED UINT32_C(4)
#define RT_CARRIER_STATUS_PLAN_MISMATCH UINT32_C(5)
#define RT_CARRIER_STATUS_INVALID_STATE UINT32_C(6)

typedef uint8_t rt_slot_state;
#define RT_SLOT_EMPTY UINT8_C(0)
#define RT_SLOT_INITIALIZED UINT8_C(1)
#define RT_SLOT_CLAIMED UINT8_C(2)
#define RT_SLOT_MOVED UINT8_C(3)
#define RT_SLOT_DROPPED UINT8_C(4)

typedef uint8_t rt_cross_mode;
#define RT_CROSS_MOVE UINT8_C(0)
#define RT_CROSS_CLONE UINT8_C(1)

typedef struct rt_value_layout rt_value_layout;
typedef struct rt_cross_allocation rt_cross_allocation;
typedef struct rt_trace_visitor rt_trace_visitor;
typedef struct rt_cross_allocator rt_cross_allocator;
typedef struct rt_cross_plan rt_cross_plan;
typedef struct rt_value_ops rt_value_ops;
typedef struct rt_key_ops rt_key_ops;
typedef struct rt_slot_header rt_slot_header;
typedef struct rt_descriptor_table_entry rt_descriptor_table_entry;
typedef struct rt_envelope_header rt_envelope_header;
typedef struct rt_typed_carrier_handle rt_typed_carrier_handle;

typedef void (*rt_trace_visit_fn)(void* context, const void* root);
typedef rt_carrier_status (*rt_cross_alloc_fn)(void* context, size_t size, size_t align, rt_cross_allocation* out);
typedef void (*rt_value_move_init_fn)(void* dst, void* src);
typedef void (*rt_value_copy_init_fn)(void* dst, const void* src);
typedef void (*rt_value_clone_init_fn)(void* dst, const void* src);
typedef void (*rt_value_drop_in_place_fn)(void* value);
typedef void (*rt_value_trace_fn)(const void* value, const rt_trace_visitor* visitor);
typedef rt_carrier_status (*rt_value_plan_cross_fn)(const void* src, rt_cross_mode mode, rt_cross_plan* out);
typedef rt_carrier_status (*rt_value_cross_move_init_fn)(void* dst, void* src, const rt_cross_plan* plan, rt_cross_allocator* allocator);
typedef rt_carrier_status (*rt_value_cross_clone_init_fn)(void* dst, const void* src, const rt_cross_plan* plan, rt_cross_allocator* allocator);
typedef uint64_t (*rt_key_hash_fn)(const void* key);
typedef uint8_t (*rt_key_equal_fn)(const void* a, const void* b);

struct rt_value_layout {
    size_t size;
    size_t align;
    size_t stride;
    rt_value_flags flags;
};

struct rt_cross_allocation {
    void* storage;
    size_t size;
    size_t align;
};

struct rt_trace_visitor {
    void* context;
    rt_trace_visit_fn visit;
};

struct rt_cross_allocator {
    void* context;
    rt_cross_alloc_fn allocate;
    size_t remaining_bytes;
    size_t remaining_allocations;
};

struct rt_cross_plan {
    const rt_value_ops* ops;
    rt_cross_mode mode;
    size_t envelope_bytes;
    size_t payload_offset;
    size_t payload_bytes;
    size_t payload_align;
    size_t sidecar_bytes;
    size_t total_bytes;
    size_t sidecar_count;
};

struct rt_value_ops {
    rt_value_layout layout;
    rt_value_move_init_fn move_init;
    rt_value_copy_init_fn copy_init;
    rt_value_clone_init_fn clone_init;
    rt_value_drop_in_place_fn drop_in_place;
    rt_value_trace_fn trace;
    rt_value_plan_cross_fn plan_cross;
    rt_value_cross_move_init_fn cross_move_init;
    rt_value_cross_clone_init_fn cross_clone_init;
};

struct rt_key_ops {
    rt_value_ops value;
    rt_key_hash_fn hash;
    rt_key_equal_fn equal;
};

struct rt_slot_header {
    rt_slot_state state;
};

struct rt_descriptor_table_entry {
    const rt_value_ops* ops;
    size_t payload_offset;
    size_t payload_align;
};

struct rt_envelope_header {
    const rt_value_ops* ops;
    size_t total_bytes;
    size_t payload_offset;
    size_t payload_bytes;
    size_t payload_align;
    uint64_t generation;
    uint32_t owner_shard_id;
    rt_slot_header slot;
};

struct rt_typed_carrier_handle {
    uintptr_t opaque;
};

const uint8_t* rt_typed_carrier_abi_manifest_hash(void);
extern const uint8_t rt_typed_carrier_abi_manifest_identity[];
void __surge_runtime_abi_typed_carrier_v2_5c95dc2f8fe5939fcd21ee528515403a3b5bc8c083fd002e3b40f968b9b389e6(void);

#ifdef __cplusplus
}
#endif

#endif
// clang-format on
