// Code generated by abi-manifest-gen; DO NOT EDIT.
// clang-format off
#ifndef SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_CHECKS_GENERATED_H
#define SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_CHECKS_GENERATED_H

#include "rt_typed_carrier_abi.generated.h"

#define SURGE_ABI_ALIGN_UP(value, align) (((value) + (align) - 1u) / (align) * (align))
#define SURGE_ABI_MAX(left, right) ((left) > (right) ? (left) : (right))

_Static_assert(sizeof(rt_value_flags) == sizeof(uint64_t), "rt_value_flags width drift");
_Static_assert(RT_VALUE_FLAG_COPY == UINT64_C(1), "RT_VALUE_FLAG_COPY value drift");
_Static_assert(RT_VALUE_FLAG_CLONABLE == UINT64_C(2), "RT_VALUE_FLAG_CLONABLE value drift");
_Static_assert(RT_VALUE_FLAG_DROPPABLE == UINT64_C(4), "RT_VALUE_FLAG_DROPPABLE value drift");
_Static_assert(RT_VALUE_FLAG_TRACEABLE == UINT64_C(8), "RT_VALUE_FLAG_TRACEABLE value drift");
_Static_assert(RT_VALUE_FLAG_SHARD_MOVABLE == UINT64_C(16), "RT_VALUE_FLAG_SHARD_MOVABLE value drift");
_Static_assert(RT_VALUE_FLAG_CROSS_CLONABLE == UINT64_C(32), "RT_VALUE_FLAG_CROSS_CLONABLE value drift");

_Static_assert(sizeof(rt_carrier_status) == sizeof(uint32_t), "rt_carrier_status width drift");
_Static_assert(RT_CARRIER_STATUS_OK == UINT32_C(0), "RT_CARRIER_STATUS_OK value drift");
_Static_assert(RT_CARRIER_STATUS_OVERFLOW == UINT32_C(1), "RT_CARRIER_STATUS_OVERFLOW value drift");
_Static_assert(RT_CARRIER_STATUS_CAPACITY == UINT32_C(2), "RT_CARRIER_STATUS_CAPACITY value drift");
_Static_assert(RT_CARRIER_STATUS_STALE_GENERATION == UINT32_C(3), "RT_CARRIER_STATUS_STALE_GENERATION value drift");
_Static_assert(RT_CARRIER_STATUS_PUBLICATION_REJECTED == UINT32_C(4), "RT_CARRIER_STATUS_PUBLICATION_REJECTED value drift");
_Static_assert(RT_CARRIER_STATUS_PLAN_MISMATCH == UINT32_C(5), "RT_CARRIER_STATUS_PLAN_MISMATCH value drift");
_Static_assert(RT_CARRIER_STATUS_INVALID_STATE == UINT32_C(6), "RT_CARRIER_STATUS_INVALID_STATE value drift");

_Static_assert(sizeof(rt_slot_state) == sizeof(uint8_t), "rt_slot_state width drift");
_Static_assert(RT_SLOT_EMPTY == UINT8_C(0), "RT_SLOT_EMPTY value drift");
_Static_assert(RT_SLOT_INITIALIZED == UINT8_C(1), "RT_SLOT_INITIALIZED value drift");
_Static_assert(RT_SLOT_CLAIMED == UINT8_C(2), "RT_SLOT_CLAIMED value drift");
_Static_assert(RT_SLOT_MOVED == UINT8_C(3), "RT_SLOT_MOVED value drift");
_Static_assert(RT_SLOT_DROPPED == UINT8_C(4), "RT_SLOT_DROPPED value drift");

_Static_assert(sizeof(rt_cross_mode) == sizeof(uint8_t), "rt_cross_mode width drift");
_Static_assert(RT_CROSS_MOVE == UINT8_C(0), "RT_CROSS_MOVE value drift");
_Static_assert(RT_CROSS_CLONE == UINT8_C(1), "RT_CROSS_CLONE value drift");

_Static_assert(sizeof(((rt_value_layout*)0)->size) == sizeof(size_t), "rt_value_layout.size type drift");
_Static_assert(offsetof(rt_value_layout, size) == 0u, "rt_value_layout.size offset drift");
_Static_assert(sizeof(((rt_value_layout*)0)->align) == sizeof(size_t), "rt_value_layout.align type drift");
_Static_assert(offsetof(rt_value_layout, align) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_layout, size) + sizeof(((rt_value_layout*)0)->size), _Alignof(size_t)), "rt_value_layout.align offset drift");
_Static_assert(sizeof(((rt_value_layout*)0)->stride) == sizeof(size_t), "rt_value_layout.stride type drift");
_Static_assert(offsetof(rt_value_layout, stride) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_layout, align) + sizeof(((rt_value_layout*)0)->align), _Alignof(size_t)), "rt_value_layout.stride offset drift");
_Static_assert(sizeof(((rt_value_layout*)0)->flags) == sizeof(rt_value_flags), "rt_value_layout.flags type drift");
_Static_assert(offsetof(rt_value_layout, flags) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_layout, stride) + sizeof(((rt_value_layout*)0)->stride), _Alignof(rt_value_flags)), "rt_value_layout.flags offset drift");
_Static_assert(_Alignof(rt_value_layout) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(rt_value_flags)), "rt_value_layout alignment drift");
_Static_assert(sizeof(rt_value_layout) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_layout, flags) + sizeof(((rt_value_layout*)0)->flags), _Alignof(rt_value_layout)), "rt_value_layout size drift");

_Static_assert(sizeof(((rt_cross_allocation*)0)->storage) == sizeof(void*), "rt_cross_allocation.storage type drift");
_Static_assert(offsetof(rt_cross_allocation, storage) == 0u, "rt_cross_allocation.storage offset drift");
_Static_assert(sizeof(((rt_cross_allocation*)0)->size) == sizeof(size_t), "rt_cross_allocation.size type drift");
_Static_assert(offsetof(rt_cross_allocation, size) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocation, storage) + sizeof(((rt_cross_allocation*)0)->storage), _Alignof(size_t)), "rt_cross_allocation.size offset drift");
_Static_assert(sizeof(((rt_cross_allocation*)0)->align) == sizeof(size_t), "rt_cross_allocation.align type drift");
_Static_assert(offsetof(rt_cross_allocation, align) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocation, size) + sizeof(((rt_cross_allocation*)0)->size), _Alignof(size_t)), "rt_cross_allocation.align offset drift");
_Static_assert(_Alignof(rt_cross_allocation) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(void*)), _Alignof(size_t)), _Alignof(size_t)), "rt_cross_allocation alignment drift");
_Static_assert(sizeof(rt_cross_allocation) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocation, align) + sizeof(((rt_cross_allocation*)0)->align), _Alignof(rt_cross_allocation)), "rt_cross_allocation size drift");

_Static_assert(sizeof(((rt_trace_visitor*)0)->context) == sizeof(void*), "rt_trace_visitor.context type drift");
_Static_assert(offsetof(rt_trace_visitor, context) == 0u, "rt_trace_visitor.context offset drift");
_Static_assert(sizeof(((rt_trace_visitor*)0)->visit) == sizeof(rt_trace_visit_fn), "rt_trace_visitor.visit type drift");
_Static_assert(offsetof(rt_trace_visitor, visit) == SURGE_ABI_ALIGN_UP(offsetof(rt_trace_visitor, context) + sizeof(((rt_trace_visitor*)0)->context), _Alignof(rt_trace_visit_fn)), "rt_trace_visitor.visit offset drift");
_Static_assert(_Alignof(rt_trace_visitor) == SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(void*)), _Alignof(rt_trace_visit_fn)), "rt_trace_visitor alignment drift");
_Static_assert(sizeof(rt_trace_visitor) == SURGE_ABI_ALIGN_UP(offsetof(rt_trace_visitor, visit) + sizeof(((rt_trace_visitor*)0)->visit), _Alignof(rt_trace_visitor)), "rt_trace_visitor size drift");

_Static_assert(sizeof(((rt_cross_allocator*)0)->context) == sizeof(void*), "rt_cross_allocator.context type drift");
_Static_assert(offsetof(rt_cross_allocator, context) == 0u, "rt_cross_allocator.context offset drift");
_Static_assert(sizeof(((rt_cross_allocator*)0)->allocate) == sizeof(rt_cross_alloc_fn), "rt_cross_allocator.allocate type drift");
_Static_assert(offsetof(rt_cross_allocator, allocate) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocator, context) + sizeof(((rt_cross_allocator*)0)->context), _Alignof(rt_cross_alloc_fn)), "rt_cross_allocator.allocate offset drift");
_Static_assert(sizeof(((rt_cross_allocator*)0)->remaining_bytes) == sizeof(size_t), "rt_cross_allocator.remaining_bytes type drift");
_Static_assert(offsetof(rt_cross_allocator, remaining_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocator, allocate) + sizeof(((rt_cross_allocator*)0)->allocate), _Alignof(size_t)), "rt_cross_allocator.remaining_bytes offset drift");
_Static_assert(sizeof(((rt_cross_allocator*)0)->remaining_allocations) == sizeof(size_t), "rt_cross_allocator.remaining_allocations type drift");
_Static_assert(offsetof(rt_cross_allocator, remaining_allocations) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocator, remaining_bytes) + sizeof(((rt_cross_allocator*)0)->remaining_bytes), _Alignof(size_t)), "rt_cross_allocator.remaining_allocations offset drift");
_Static_assert(_Alignof(rt_cross_allocator) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(void*)), _Alignof(rt_cross_alloc_fn)), _Alignof(size_t)), _Alignof(size_t)), "rt_cross_allocator alignment drift");
_Static_assert(sizeof(rt_cross_allocator) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_allocator, remaining_allocations) + sizeof(((rt_cross_allocator*)0)->remaining_allocations), _Alignof(rt_cross_allocator)), "rt_cross_allocator size drift");

_Static_assert(sizeof(((rt_cross_plan*)0)->ops) == sizeof(const rt_value_ops*), "rt_cross_plan.ops type drift");
_Static_assert(offsetof(rt_cross_plan, ops) == 0u, "rt_cross_plan.ops offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->mode) == sizeof(rt_cross_mode), "rt_cross_plan.mode type drift");
_Static_assert(offsetof(rt_cross_plan, mode) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, ops) + sizeof(((rt_cross_plan*)0)->ops), _Alignof(rt_cross_mode)), "rt_cross_plan.mode offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->envelope_bytes) == sizeof(size_t), "rt_cross_plan.envelope_bytes type drift");
_Static_assert(offsetof(rt_cross_plan, envelope_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, mode) + sizeof(((rt_cross_plan*)0)->mode), _Alignof(size_t)), "rt_cross_plan.envelope_bytes offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->payload_offset) == sizeof(size_t), "rt_cross_plan.payload_offset type drift");
_Static_assert(offsetof(rt_cross_plan, payload_offset) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, envelope_bytes) + sizeof(((rt_cross_plan*)0)->envelope_bytes), _Alignof(size_t)), "rt_cross_plan.payload_offset offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->payload_bytes) == sizeof(size_t), "rt_cross_plan.payload_bytes type drift");
_Static_assert(offsetof(rt_cross_plan, payload_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, payload_offset) + sizeof(((rt_cross_plan*)0)->payload_offset), _Alignof(size_t)), "rt_cross_plan.payload_bytes offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->payload_align) == sizeof(size_t), "rt_cross_plan.payload_align type drift");
_Static_assert(offsetof(rt_cross_plan, payload_align) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, payload_bytes) + sizeof(((rt_cross_plan*)0)->payload_bytes), _Alignof(size_t)), "rt_cross_plan.payload_align offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->sidecar_bytes) == sizeof(size_t), "rt_cross_plan.sidecar_bytes type drift");
_Static_assert(offsetof(rt_cross_plan, sidecar_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, payload_align) + sizeof(((rt_cross_plan*)0)->payload_align), _Alignof(size_t)), "rt_cross_plan.sidecar_bytes offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->total_bytes) == sizeof(size_t), "rt_cross_plan.total_bytes type drift");
_Static_assert(offsetof(rt_cross_plan, total_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, sidecar_bytes) + sizeof(((rt_cross_plan*)0)->sidecar_bytes), _Alignof(size_t)), "rt_cross_plan.total_bytes offset drift");
_Static_assert(sizeof(((rt_cross_plan*)0)->sidecar_count) == sizeof(size_t), "rt_cross_plan.sidecar_count type drift");
_Static_assert(offsetof(rt_cross_plan, sidecar_count) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, total_bytes) + sizeof(((rt_cross_plan*)0)->total_bytes), _Alignof(size_t)), "rt_cross_plan.sidecar_count offset drift");
_Static_assert(_Alignof(rt_cross_plan) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(const rt_value_ops*)), _Alignof(rt_cross_mode)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), "rt_cross_plan alignment drift");
_Static_assert(sizeof(rt_cross_plan) == SURGE_ABI_ALIGN_UP(offsetof(rt_cross_plan, sidecar_count) + sizeof(((rt_cross_plan*)0)->sidecar_count), _Alignof(rt_cross_plan)), "rt_cross_plan size drift");

_Static_assert(sizeof(((rt_value_ops*)0)->layout) == sizeof(rt_value_layout), "rt_value_ops.layout type drift");
_Static_assert(offsetof(rt_value_ops, layout) == 0u, "rt_value_ops.layout offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->move_init) == sizeof(rt_value_move_init_fn), "rt_value_ops.move_init type drift");
_Static_assert(offsetof(rt_value_ops, move_init) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, layout) + sizeof(((rt_value_ops*)0)->layout), _Alignof(rt_value_move_init_fn)), "rt_value_ops.move_init offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->copy_init) == sizeof(rt_value_copy_init_fn), "rt_value_ops.copy_init type drift");
_Static_assert(offsetof(rt_value_ops, copy_init) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, move_init) + sizeof(((rt_value_ops*)0)->move_init), _Alignof(rt_value_copy_init_fn)), "rt_value_ops.copy_init offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->clone_init) == sizeof(rt_value_clone_init_fn), "rt_value_ops.clone_init type drift");
_Static_assert(offsetof(rt_value_ops, clone_init) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, copy_init) + sizeof(((rt_value_ops*)0)->copy_init), _Alignof(rt_value_clone_init_fn)), "rt_value_ops.clone_init offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->drop_in_place) == sizeof(rt_value_drop_in_place_fn), "rt_value_ops.drop_in_place type drift");
_Static_assert(offsetof(rt_value_ops, drop_in_place) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, clone_init) + sizeof(((rt_value_ops*)0)->clone_init), _Alignof(rt_value_drop_in_place_fn)), "rt_value_ops.drop_in_place offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->trace) == sizeof(rt_value_trace_fn), "rt_value_ops.trace type drift");
_Static_assert(offsetof(rt_value_ops, trace) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, drop_in_place) + sizeof(((rt_value_ops*)0)->drop_in_place), _Alignof(rt_value_trace_fn)), "rt_value_ops.trace offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->plan_cross) == sizeof(rt_value_plan_cross_fn), "rt_value_ops.plan_cross type drift");
_Static_assert(offsetof(rt_value_ops, plan_cross) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, trace) + sizeof(((rt_value_ops*)0)->trace), _Alignof(rt_value_plan_cross_fn)), "rt_value_ops.plan_cross offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->cross_move_init) == sizeof(rt_value_cross_move_init_fn), "rt_value_ops.cross_move_init type drift");
_Static_assert(offsetof(rt_value_ops, cross_move_init) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, plan_cross) + sizeof(((rt_value_ops*)0)->plan_cross), _Alignof(rt_value_cross_move_init_fn)), "rt_value_ops.cross_move_init offset drift");
_Static_assert(sizeof(((rt_value_ops*)0)->cross_clone_init) == sizeof(rt_value_cross_clone_init_fn), "rt_value_ops.cross_clone_init type drift");
_Static_assert(offsetof(rt_value_ops, cross_clone_init) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, cross_move_init) + sizeof(((rt_value_ops*)0)->cross_move_init), _Alignof(rt_value_cross_clone_init_fn)), "rt_value_ops.cross_clone_init offset drift");
_Static_assert(_Alignof(rt_value_ops) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(rt_value_layout)), _Alignof(rt_value_move_init_fn)), _Alignof(rt_value_copy_init_fn)), _Alignof(rt_value_clone_init_fn)), _Alignof(rt_value_drop_in_place_fn)), _Alignof(rt_value_trace_fn)), _Alignof(rt_value_plan_cross_fn)), _Alignof(rt_value_cross_move_init_fn)), _Alignof(rt_value_cross_clone_init_fn)), "rt_value_ops alignment drift");
_Static_assert(sizeof(rt_value_ops) == SURGE_ABI_ALIGN_UP(offsetof(rt_value_ops, cross_clone_init) + sizeof(((rt_value_ops*)0)->cross_clone_init), _Alignof(rt_value_ops)), "rt_value_ops size drift");

_Static_assert(sizeof(((rt_key_ops*)0)->value) == sizeof(rt_value_ops), "rt_key_ops.value type drift");
_Static_assert(offsetof(rt_key_ops, value) == 0u, "rt_key_ops.value offset drift");
_Static_assert(sizeof(((rt_key_ops*)0)->hash) == sizeof(rt_key_hash_fn), "rt_key_ops.hash type drift");
_Static_assert(offsetof(rt_key_ops, hash) == SURGE_ABI_ALIGN_UP(offsetof(rt_key_ops, value) + sizeof(((rt_key_ops*)0)->value), _Alignof(rt_key_hash_fn)), "rt_key_ops.hash offset drift");
_Static_assert(sizeof(((rt_key_ops*)0)->equal) == sizeof(rt_key_equal_fn), "rt_key_ops.equal type drift");
_Static_assert(offsetof(rt_key_ops, equal) == SURGE_ABI_ALIGN_UP(offsetof(rt_key_ops, hash) + sizeof(((rt_key_ops*)0)->hash), _Alignof(rt_key_equal_fn)), "rt_key_ops.equal offset drift");
_Static_assert(_Alignof(rt_key_ops) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(rt_value_ops)), _Alignof(rt_key_hash_fn)), _Alignof(rt_key_equal_fn)), "rt_key_ops alignment drift");
_Static_assert(sizeof(rt_key_ops) == SURGE_ABI_ALIGN_UP(offsetof(rt_key_ops, equal) + sizeof(((rt_key_ops*)0)->equal), _Alignof(rt_key_ops)), "rt_key_ops size drift");

_Static_assert(sizeof(((rt_slot_header*)0)->state) == sizeof(rt_slot_state), "rt_slot_header.state type drift");
_Static_assert(offsetof(rt_slot_header, state) == 0u, "rt_slot_header.state offset drift");
_Static_assert(_Alignof(rt_slot_header) == SURGE_ABI_MAX(1u, _Alignof(rt_slot_state)), "rt_slot_header alignment drift");
_Static_assert(sizeof(rt_slot_header) == SURGE_ABI_ALIGN_UP(offsetof(rt_slot_header, state) + sizeof(((rt_slot_header*)0)->state), _Alignof(rt_slot_header)), "rt_slot_header size drift");

_Static_assert(sizeof(((rt_descriptor_table_entry*)0)->ops) == sizeof(const rt_value_ops*), "rt_descriptor_table_entry.ops type drift");
_Static_assert(offsetof(rt_descriptor_table_entry, ops) == 0u, "rt_descriptor_table_entry.ops offset drift");
_Static_assert(sizeof(((rt_descriptor_table_entry*)0)->payload_offset) == sizeof(size_t), "rt_descriptor_table_entry.payload_offset type drift");
_Static_assert(offsetof(rt_descriptor_table_entry, payload_offset) == SURGE_ABI_ALIGN_UP(offsetof(rt_descriptor_table_entry, ops) + sizeof(((rt_descriptor_table_entry*)0)->ops), _Alignof(size_t)), "rt_descriptor_table_entry.payload_offset offset drift");
_Static_assert(sizeof(((rt_descriptor_table_entry*)0)->payload_align) == sizeof(size_t), "rt_descriptor_table_entry.payload_align type drift");
_Static_assert(offsetof(rt_descriptor_table_entry, payload_align) == SURGE_ABI_ALIGN_UP(offsetof(rt_descriptor_table_entry, payload_offset) + sizeof(((rt_descriptor_table_entry*)0)->payload_offset), _Alignof(size_t)), "rt_descriptor_table_entry.payload_align offset drift");
_Static_assert(_Alignof(rt_descriptor_table_entry) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(const rt_value_ops*)), _Alignof(size_t)), _Alignof(size_t)), "rt_descriptor_table_entry alignment drift");
_Static_assert(sizeof(rt_descriptor_table_entry) == SURGE_ABI_ALIGN_UP(offsetof(rt_descriptor_table_entry, payload_align) + sizeof(((rt_descriptor_table_entry*)0)->payload_align), _Alignof(rt_descriptor_table_entry)), "rt_descriptor_table_entry size drift");

_Static_assert(sizeof(((rt_envelope_header*)0)->ops) == sizeof(const rt_value_ops*), "rt_envelope_header.ops type drift");
_Static_assert(offsetof(rt_envelope_header, ops) == 0u, "rt_envelope_header.ops offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->total_bytes) == sizeof(size_t), "rt_envelope_header.total_bytes type drift");
_Static_assert(offsetof(rt_envelope_header, total_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, ops) + sizeof(((rt_envelope_header*)0)->ops), _Alignof(size_t)), "rt_envelope_header.total_bytes offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->payload_offset) == sizeof(size_t), "rt_envelope_header.payload_offset type drift");
_Static_assert(offsetof(rt_envelope_header, payload_offset) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, total_bytes) + sizeof(((rt_envelope_header*)0)->total_bytes), _Alignof(size_t)), "rt_envelope_header.payload_offset offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->payload_bytes) == sizeof(size_t), "rt_envelope_header.payload_bytes type drift");
_Static_assert(offsetof(rt_envelope_header, payload_bytes) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, payload_offset) + sizeof(((rt_envelope_header*)0)->payload_offset), _Alignof(size_t)), "rt_envelope_header.payload_bytes offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->payload_align) == sizeof(size_t), "rt_envelope_header.payload_align type drift");
_Static_assert(offsetof(rt_envelope_header, payload_align) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, payload_bytes) + sizeof(((rt_envelope_header*)0)->payload_bytes), _Alignof(size_t)), "rt_envelope_header.payload_align offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->generation) == sizeof(uint64_t), "rt_envelope_header.generation type drift");
_Static_assert(offsetof(rt_envelope_header, generation) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, payload_align) + sizeof(((rt_envelope_header*)0)->payload_align), _Alignof(uint64_t)), "rt_envelope_header.generation offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->owner_shard_id) == sizeof(uint32_t), "rt_envelope_header.owner_shard_id type drift");
_Static_assert(offsetof(rt_envelope_header, owner_shard_id) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, generation) + sizeof(((rt_envelope_header*)0)->generation), _Alignof(uint32_t)), "rt_envelope_header.owner_shard_id offset drift");
_Static_assert(sizeof(((rt_envelope_header*)0)->slot) == sizeof(rt_slot_header), "rt_envelope_header.slot type drift");
_Static_assert(offsetof(rt_envelope_header, slot) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, owner_shard_id) + sizeof(((rt_envelope_header*)0)->owner_shard_id), _Alignof(rt_slot_header)), "rt_envelope_header.slot offset drift");
_Static_assert(_Alignof(rt_envelope_header) == SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(SURGE_ABI_MAX(1u, _Alignof(const rt_value_ops*)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(size_t)), _Alignof(uint64_t)), _Alignof(uint32_t)), _Alignof(rt_slot_header)), "rt_envelope_header alignment drift");
_Static_assert(sizeof(rt_envelope_header) == SURGE_ABI_ALIGN_UP(offsetof(rt_envelope_header, slot) + sizeof(((rt_envelope_header*)0)->slot), _Alignof(rt_envelope_header)), "rt_envelope_header size drift");

_Static_assert(sizeof(((rt_typed_carrier_handle*)0)->opaque) == sizeof(uintptr_t), "rt_typed_carrier_handle.opaque type drift");
_Static_assert(offsetof(rt_typed_carrier_handle, opaque) == 0u, "rt_typed_carrier_handle.opaque offset drift");
_Static_assert(_Alignof(rt_typed_carrier_handle) == SURGE_ABI_MAX(1u, _Alignof(uintptr_t)), "rt_typed_carrier_handle alignment drift");
_Static_assert(sizeof(rt_typed_carrier_handle) == SURGE_ABI_ALIGN_UP(offsetof(rt_typed_carrier_handle, opaque) + sizeof(((rt_typed_carrier_handle*)0)->opaque), _Alignof(rt_typed_carrier_handle)), "rt_typed_carrier_handle size drift");

#if defined(__GNUC__) || defined(__clang__)
_Static_assert(__builtin_types_compatible_p(rt_trace_visit_fn, void (*)(void*, const void*)), "rt_trace_visit_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_cross_alloc_fn, rt_carrier_status (*)(void*, size_t, size_t, rt_cross_allocation*)), "rt_cross_alloc_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_move_init_fn, void (*)(void*, void*)), "rt_value_move_init_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_copy_init_fn, void (*)(void*, const void*)), "rt_value_copy_init_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_clone_init_fn, void (*)(void*, const void*)), "rt_value_clone_init_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_drop_in_place_fn, void (*)(void*)), "rt_value_drop_in_place_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_trace_fn, void (*)(const void*, const rt_trace_visitor*)), "rt_value_trace_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_plan_cross_fn, rt_carrier_status (*)(const void*, rt_cross_mode, rt_cross_plan*)), "rt_value_plan_cross_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_cross_move_init_fn, rt_carrier_status (*)(void*, void*, const rt_cross_plan*, rt_cross_allocator*)), "rt_value_cross_move_init_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_value_cross_clone_init_fn, rt_carrier_status (*)(void*, const void*, const rt_cross_plan*, rt_cross_allocator*)), "rt_value_cross_clone_init_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_key_hash_fn, uint64_t (*)(const void*)), "rt_key_hash_fn signature drift");
_Static_assert(__builtin_types_compatible_p(rt_key_equal_fn, uint8_t (*)(const void*, const void*)), "rt_key_equal_fn signature drift");
_Static_assert(__builtin_types_compatible_p(__typeof__(&rt_typed_carrier_abi_manifest_hash), const uint8_t* (*)(void)), "rt_typed_carrier_abi_manifest_hash signature drift");
_Static_assert(__builtin_types_compatible_p(__typeof__(&rt_value_copy_init_unbound_trap), void (*)(void*, const void*)), "rt_value_copy_init_unbound_trap signature drift");
#endif

#undef SURGE_ABI_MAX
#undef SURGE_ABI_ALIGN_UP

#endif
// clang-format on
