// Code generated by abi-manifest-gen; DO NOT EDIT.
// clang-format off
#include "rt_typed_carrier_abi_checks.generated.h"

#if defined(__GNUC__) || defined(__clang__)
#define SURGE_ABI_USED __attribute__((used))
#define SURGE_ABI_NOINLINE __attribute__((noinline))
#define SURGE_ABI_VISIBLE __attribute__((visibility("default")))
#else
#define SURGE_ABI_USED
#define SURGE_ABI_NOINLINE
#define SURGE_ABI_VISIBLE
#endif

#if defined(__has_attribute)
#if __has_attribute(retain)
#define SURGE_ABI_RETAIN __attribute__((retain))
#endif
#endif
#ifndef SURGE_ABI_RETAIN
#define SURGE_ABI_RETAIN
#endif

const uint8_t rt_typed_carrier_abi_manifest_identity[] = "f30fcfb03b62d105dab0cd21d57a3dcc029b0e7ae10a337e966079033608650a";

const uint8_t* rt_typed_carrier_abi_manifest_hash(void) {
    return rt_typed_carrier_abi_manifest_identity;
}

static volatile uint8_t rt_typed_carrier_abi_retention_anchor;

SURGE_ABI_USED SURGE_ABI_RETAIN SURGE_ABI_NOINLINE SURGE_ABI_VISIBLE void __surge_runtime_abi_typed_carrier_v2_f30fcfb03b62d105dab0cd21d57a3dcc029b0e7ae10a337e966079033608650a(
    void) {
    (void)rt_typed_carrier_abi_retention_anchor;
}

#undef SURGE_ABI_RETAIN
#undef SURGE_ABI_VISIBLE
#undef SURGE_ABI_NOINLINE
#undef SURGE_ABI_USED
// clang-format on
