package sema

import (
	"surge/internal/source"
	"surge/internal/symbols"
)

type builtinMagicSpec struct {
	receiver string
	name     string
	params   []string
	result   string
}

var builtinMagic = []builtinMagicSpec{
	{receiver: "[]", name: "__add", params: []string{"[]", "[]"}, result: "[]"},
	{receiver: "int", name: "__add", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__sub", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__mul", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__div", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__mod", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__bit_and", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__bit_or", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__bit_xor", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__shl", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__shr", params: []string{"int", "int"}, result: "int"},
	{receiver: "int", name: "__lt", params: []string{"int", "int"}, result: "bool"},
	{receiver: "int", name: "__le", params: []string{"int", "int"}, result: "bool"},
	{receiver: "int", name: "__eq", params: []string{"int", "int"}, result: "bool"},
	{receiver: "int", name: "__ne", params: []string{"int", "int"}, result: "bool"},
	{receiver: "int", name: "__ge", params: []string{"int", "int"}, result: "bool"},
	{receiver: "int", name: "__gt", params: []string{"int", "int"}, result: "bool"},
	{receiver: "int", name: "__pos", params: []string{"int"}, result: "int"},
	{receiver: "int", name: "__neg", params: []string{"int"}, result: "int"},
	{receiver: "int", name: "__to", params: []string{"int", "string"}, result: "string"},
	{receiver: "int", name: "__to", params: []string{"int", "float"}, result: "float"},
	{receiver: "int", name: "__to", params: []string{"int", "uint"}, result: "uint"},
	{receiver: "int", name: "__to", params: []string{"int", "int8"}, result: "int8"},
	{receiver: "int", name: "__to", params: []string{"int", "int16"}, result: "int16"},
	{receiver: "int", name: "__to", params: []string{"int", "int32"}, result: "int32"},
	{receiver: "int", name: "__to", params: []string{"int", "int64"}, result: "int64"},
	{receiver: "int", name: "__to", params: []string{"int", "uint8"}, result: "uint8"},
	{receiver: "int", name: "__to", params: []string{"int", "uint16"}, result: "uint16"},
	{receiver: "int", name: "__to", params: []string{"int", "uint32"}, result: "uint32"},
	{receiver: "int", name: "__to", params: []string{"int", "uint64"}, result: "uint64"},
	{receiver: "int", name: "__to", params: []string{"int", "float16"}, result: "float16"},
	{receiver: "int", name: "__to", params: []string{"int", "float32"}, result: "float32"},
	{receiver: "int", name: "__to", params: []string{"int", "float64"}, result: "float64"},

	{receiver: "uint", name: "__add", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__sub", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__mul", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__div", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__mod", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__bit_and", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__bit_or", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__bit_xor", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__shl", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__shr", params: []string{"uint", "uint"}, result: "uint"},
	{receiver: "uint", name: "__lt", params: []string{"uint", "uint"}, result: "bool"},
	{receiver: "uint", name: "__le", params: []string{"uint", "uint"}, result: "bool"},
	{receiver: "uint", name: "__eq", params: []string{"uint", "uint"}, result: "bool"},
	{receiver: "uint", name: "__ne", params: []string{"uint", "uint"}, result: "bool"},
	{receiver: "uint", name: "__ge", params: []string{"uint", "uint"}, result: "bool"},
	{receiver: "uint", name: "__gt", params: []string{"uint", "uint"}, result: "bool"},
	{receiver: "uint", name: "__pos", params: []string{"uint"}, result: "uint"},
	{receiver: "uint", name: "__to", params: []string{"uint", "string"}, result: "string"},
	{receiver: "uint", name: "__to", params: []string{"uint", "int"}, result: "int"},
	{receiver: "uint", name: "__to", params: []string{"uint", "float"}, result: "float"},
	{receiver: "uint", name: "__to", params: []string{"uint", "int8"}, result: "int8"},
	{receiver: "uint", name: "__to", params: []string{"uint", "int16"}, result: "int16"},
	{receiver: "uint", name: "__to", params: []string{"uint", "int32"}, result: "int32"},
	{receiver: "uint", name: "__to", params: []string{"uint", "int64"}, result: "int64"},
	{receiver: "uint", name: "__to", params: []string{"uint", "uint8"}, result: "uint8"},
	{receiver: "uint", name: "__to", params: []string{"uint", "uint16"}, result: "uint16"},
	{receiver: "uint", name: "__to", params: []string{"uint", "uint32"}, result: "uint32"},
	{receiver: "uint", name: "__to", params: []string{"uint", "uint64"}, result: "uint64"},
	{receiver: "uint", name: "__to", params: []string{"uint", "float16"}, result: "float16"},
	{receiver: "uint", name: "__to", params: []string{"uint", "float32"}, result: "float32"},
	{receiver: "uint", name: "__to", params: []string{"uint", "float64"}, result: "float64"},

	{receiver: "int8", name: "__add", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__sub", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__mul", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__div", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__mod", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__bit_and", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__bit_or", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__bit_xor", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__shl", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__shr", params: []string{"int8", "int8"}, result: "int8"},
	{receiver: "int8", name: "__lt", params: []string{"int8", "int8"}, result: "bool"},
	{receiver: "int8", name: "__le", params: []string{"int8", "int8"}, result: "bool"},
	{receiver: "int8", name: "__eq", params: []string{"int8", "int8"}, result: "bool"},
	{receiver: "int8", name: "__ne", params: []string{"int8", "int8"}, result: "bool"},
	{receiver: "int8", name: "__ge", params: []string{"int8", "int8"}, result: "bool"},
	{receiver: "int8", name: "__gt", params: []string{"int8", "int8"}, result: "bool"},
	{receiver: "int8", name: "__pos", params: []string{"int8"}, result: "int8"},
	{receiver: "int8", name: "__neg", params: []string{"int8"}, result: "int8"},
	{receiver: "int8", name: "__abs", params: []string{"int8"}, result: "int8"},
	{receiver: "int8", name: "__to", params: []string{"int8", "int"}, result: "int"},
	{receiver: "int8", name: "__to", params: []string{"int8", "int16"}, result: "int16"},
	{receiver: "int8", name: "__to", params: []string{"int8", "int32"}, result: "int32"},
	{receiver: "int8", name: "__to", params: []string{"int8", "int64"}, result: "int64"},

	{receiver: "int16", name: "__add", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__sub", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__mul", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__div", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__mod", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__bit_and", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__bit_or", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__bit_xor", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__shl", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__shr", params: []string{"int16", "int16"}, result: "int16"},
	{receiver: "int16", name: "__lt", params: []string{"int16", "int16"}, result: "bool"},
	{receiver: "int16", name: "__le", params: []string{"int16", "int16"}, result: "bool"},
	{receiver: "int16", name: "__eq", params: []string{"int16", "int16"}, result: "bool"},
	{receiver: "int16", name: "__ne", params: []string{"int16", "int16"}, result: "bool"},
	{receiver: "int16", name: "__ge", params: []string{"int16", "int16"}, result: "bool"},
	{receiver: "int16", name: "__gt", params: []string{"int16", "int16"}, result: "bool"},
	{receiver: "int16", name: "__pos", params: []string{"int16"}, result: "int16"},
	{receiver: "int16", name: "__neg", params: []string{"int16"}, result: "int16"},
	{receiver: "int16", name: "__abs", params: []string{"int16"}, result: "int16"},
	{receiver: "int16", name: "__to", params: []string{"int16", "int"}, result: "int"},
	{receiver: "int16", name: "__to", params: []string{"int16", "int8"}, result: "int8"},
	{receiver: "int16", name: "__to", params: []string{"int16", "int32"}, result: "int32"},
	{receiver: "int16", name: "__to", params: []string{"int16", "int64"}, result: "int64"},

	{receiver: "int32", name: "__add", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__sub", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__mul", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__div", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__mod", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__bit_and", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__bit_or", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__bit_xor", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__shl", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__shr", params: []string{"int32", "int32"}, result: "int32"},
	{receiver: "int32", name: "__lt", params: []string{"int32", "int32"}, result: "bool"},
	{receiver: "int32", name: "__le", params: []string{"int32", "int32"}, result: "bool"},
	{receiver: "int32", name: "__eq", params: []string{"int32", "int32"}, result: "bool"},
	{receiver: "int32", name: "__ne", params: []string{"int32", "int32"}, result: "bool"},
	{receiver: "int32", name: "__ge", params: []string{"int32", "int32"}, result: "bool"},
	{receiver: "int32", name: "__gt", params: []string{"int32", "int32"}, result: "bool"},
	{receiver: "int32", name: "__pos", params: []string{"int32"}, result: "int32"},
	{receiver: "int32", name: "__neg", params: []string{"int32"}, result: "int32"},
	{receiver: "int32", name: "__abs", params: []string{"int32"}, result: "int32"},
	{receiver: "int32", name: "__to", params: []string{"int32", "int"}, result: "int"},
	{receiver: "int32", name: "__to", params: []string{"int32", "int8"}, result: "int8"},
	{receiver: "int32", name: "__to", params: []string{"int32", "int16"}, result: "int16"},
	{receiver: "int32", name: "__to", params: []string{"int32", "int64"}, result: "int64"},

	{receiver: "int64", name: "__add", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__sub", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__mul", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__div", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__mod", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__bit_and", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__bit_or", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__bit_xor", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__shl", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__shr", params: []string{"int64", "int64"}, result: "int64"},
	{receiver: "int64", name: "__lt", params: []string{"int64", "int64"}, result: "bool"},
	{receiver: "int64", name: "__le", params: []string{"int64", "int64"}, result: "bool"},
	{receiver: "int64", name: "__eq", params: []string{"int64", "int64"}, result: "bool"},
	{receiver: "int64", name: "__ne", params: []string{"int64", "int64"}, result: "bool"},
	{receiver: "int64", name: "__ge", params: []string{"int64", "int64"}, result: "bool"},
	{receiver: "int64", name: "__gt", params: []string{"int64", "int64"}, result: "bool"},
	{receiver: "int64", name: "__pos", params: []string{"int64"}, result: "int64"},
	{receiver: "int64", name: "__neg", params: []string{"int64"}, result: "int64"},
	{receiver: "int64", name: "__abs", params: []string{"int64"}, result: "int64"},
	{receiver: "int64", name: "__to", params: []string{"int64", "int"}, result: "int"},
	{receiver: "int64", name: "__to", params: []string{"int64", "int8"}, result: "int8"},
	{receiver: "int64", name: "__to", params: []string{"int64", "int16"}, result: "int16"},
	{receiver: "int64", name: "__to", params: []string{"int64", "int32"}, result: "int32"},

	{receiver: "uint8", name: "__add", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__sub", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__mul", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__div", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__mod", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__bit_and", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__bit_or", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__bit_xor", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__shl", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__shr", params: []string{"uint8", "uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__lt", params: []string{"uint8", "uint8"}, result: "bool"},
	{receiver: "uint8", name: "__le", params: []string{"uint8", "uint8"}, result: "bool"},
	{receiver: "uint8", name: "__eq", params: []string{"uint8", "uint8"}, result: "bool"},
	{receiver: "uint8", name: "__ne", params: []string{"uint8", "uint8"}, result: "bool"},
	{receiver: "uint8", name: "__ge", params: []string{"uint8", "uint8"}, result: "bool"},
	{receiver: "uint8", name: "__gt", params: []string{"uint8", "uint8"}, result: "bool"},
	{receiver: "uint8", name: "__pos", params: []string{"uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__abs", params: []string{"uint8"}, result: "uint8"},
	{receiver: "uint8", name: "__to", params: []string{"uint8", "uint"}, result: "uint"},
	{receiver: "uint8", name: "__to", params: []string{"uint8", "uint16"}, result: "uint16"},
	{receiver: "uint8", name: "__to", params: []string{"uint8", "uint32"}, result: "uint32"},
	{receiver: "uint8", name: "__to", params: []string{"uint8", "uint64"}, result: "uint64"},

	{receiver: "uint16", name: "__add", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__sub", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__mul", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__div", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__mod", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__bit_and", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__bit_or", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__bit_xor", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__shl", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__shr", params: []string{"uint16", "uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__lt", params: []string{"uint16", "uint16"}, result: "bool"},
	{receiver: "uint16", name: "__le", params: []string{"uint16", "uint16"}, result: "bool"},
	{receiver: "uint16", name: "__eq", params: []string{"uint16", "uint16"}, result: "bool"},
	{receiver: "uint16", name: "__ne", params: []string{"uint16", "uint16"}, result: "bool"},
	{receiver: "uint16", name: "__ge", params: []string{"uint16", "uint16"}, result: "bool"},
	{receiver: "uint16", name: "__gt", params: []string{"uint16", "uint16"}, result: "bool"},
	{receiver: "uint16", name: "__pos", params: []string{"uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__abs", params: []string{"uint16"}, result: "uint16"},
	{receiver: "uint16", name: "__to", params: []string{"uint16", "uint"}, result: "uint"},
	{receiver: "uint16", name: "__to", params: []string{"uint16", "uint8"}, result: "uint8"},
	{receiver: "uint16", name: "__to", params: []string{"uint16", "uint32"}, result: "uint32"},
	{receiver: "uint16", name: "__to", params: []string{"uint16", "uint64"}, result: "uint64"},

	{receiver: "uint32", name: "__add", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__sub", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__mul", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__div", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__mod", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__bit_and", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__bit_or", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__bit_xor", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__shl", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__shr", params: []string{"uint32", "uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__lt", params: []string{"uint32", "uint32"}, result: "bool"},
	{receiver: "uint32", name: "__le", params: []string{"uint32", "uint32"}, result: "bool"},
	{receiver: "uint32", name: "__eq", params: []string{"uint32", "uint32"}, result: "bool"},
	{receiver: "uint32", name: "__ne", params: []string{"uint32", "uint32"}, result: "bool"},
	{receiver: "uint32", name: "__ge", params: []string{"uint32", "uint32"}, result: "bool"},
	{receiver: "uint32", name: "__gt", params: []string{"uint32", "uint32"}, result: "bool"},
	{receiver: "uint32", name: "__pos", params: []string{"uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__abs", params: []string{"uint32"}, result: "uint32"},
	{receiver: "uint32", name: "__to", params: []string{"uint32", "uint"}, result: "uint"},
	{receiver: "uint32", name: "__to", params: []string{"uint32", "uint8"}, result: "uint8"},
	{receiver: "uint32", name: "__to", params: []string{"uint32", "uint16"}, result: "uint16"},
	{receiver: "uint32", name: "__to", params: []string{"uint32", "uint64"}, result: "uint64"},

	{receiver: "uint64", name: "__add", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__sub", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__mul", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__div", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__mod", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__bit_and", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__bit_or", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__bit_xor", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__shl", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__shr", params: []string{"uint64", "uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__lt", params: []string{"uint64", "uint64"}, result: "bool"},
	{receiver: "uint64", name: "__le", params: []string{"uint64", "uint64"}, result: "bool"},
	{receiver: "uint64", name: "__eq", params: []string{"uint64", "uint64"}, result: "bool"},
	{receiver: "uint64", name: "__ne", params: []string{"uint64", "uint64"}, result: "bool"},
	{receiver: "uint64", name: "__ge", params: []string{"uint64", "uint64"}, result: "bool"},
	{receiver: "uint64", name: "__gt", params: []string{"uint64", "uint64"}, result: "bool"},
	{receiver: "uint64", name: "__pos", params: []string{"uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__abs", params: []string{"uint64"}, result: "uint64"},
	{receiver: "uint64", name: "__to", params: []string{"uint64", "uint"}, result: "uint"},
	{receiver: "uint64", name: "__to", params: []string{"uint64", "uint8"}, result: "uint8"},
	{receiver: "uint64", name: "__to", params: []string{"uint64", "uint16"}, result: "uint16"},
	{receiver: "uint64", name: "__to", params: []string{"uint64", "uint32"}, result: "uint32"},

	{receiver: "float16", name: "__add", params: []string{"float16", "float16"}, result: "float16"},
	{receiver: "float16", name: "__sub", params: []string{"float16", "float16"}, result: "float16"},
	{receiver: "float16", name: "__mul", params: []string{"float16", "float16"}, result: "float16"},
	{receiver: "float16", name: "__div", params: []string{"float16", "float16"}, result: "float16"},
	{receiver: "float16", name: "__mod", params: []string{"float16", "float16"}, result: "float16"},
	{receiver: "float16", name: "__lt", params: []string{"float16", "float16"}, result: "bool"},
	{receiver: "float16", name: "__le", params: []string{"float16", "float16"}, result: "bool"},
	{receiver: "float16", name: "__eq", params: []string{"float16", "float16"}, result: "bool"},
	{receiver: "float16", name: "__ne", params: []string{"float16", "float16"}, result: "bool"},
	{receiver: "float16", name: "__ge", params: []string{"float16", "float16"}, result: "bool"},
	{receiver: "float16", name: "__gt", params: []string{"float16", "float16"}, result: "bool"},
	{receiver: "float16", name: "__pos", params: []string{"float16"}, result: "float16"},
	{receiver: "float16", name: "__neg", params: []string{"float16"}, result: "float16"},
	{receiver: "float16", name: "__abs", params: []string{"float16"}, result: "float16"},
	{receiver: "float16", name: "__to", params: []string{"float16", "float"}, result: "float"},
	{receiver: "float16", name: "__to", params: []string{"float16", "float32"}, result: "float32"},
	{receiver: "float16", name: "__to", params: []string{"float16", "float64"}, result: "float64"},

	{receiver: "float32", name: "__add", params: []string{"float32", "float32"}, result: "float32"},
	{receiver: "float32", name: "__sub", params: []string{"float32", "float32"}, result: "float32"},
	{receiver: "float32", name: "__mul", params: []string{"float32", "float32"}, result: "float32"},
	{receiver: "float32", name: "__div", params: []string{"float32", "float32"}, result: "float32"},
	{receiver: "float32", name: "__mod", params: []string{"float32", "float32"}, result: "float32"},
	{receiver: "float32", name: "__lt", params: []string{"float32", "float32"}, result: "bool"},
	{receiver: "float32", name: "__le", params: []string{"float32", "float32"}, result: "bool"},
	{receiver: "float32", name: "__eq", params: []string{"float32", "float32"}, result: "bool"},
	{receiver: "float32", name: "__ne", params: []string{"float32", "float32"}, result: "bool"},
	{receiver: "float32", name: "__ge", params: []string{"float32", "float32"}, result: "bool"},
	{receiver: "float32", name: "__gt", params: []string{"float32", "float32"}, result: "bool"},
	{receiver: "float32", name: "__pos", params: []string{"float32"}, result: "float32"},
	{receiver: "float32", name: "__neg", params: []string{"float32"}, result: "float32"},
	{receiver: "float32", name: "__abs", params: []string{"float32"}, result: "float32"},
	{receiver: "float32", name: "__to", params: []string{"float32", "float"}, result: "float"},
	{receiver: "float32", name: "__to", params: []string{"float32", "float16"}, result: "float16"},
	{receiver: "float32", name: "__to", params: []string{"float32", "float64"}, result: "float64"},

	{receiver: "float64", name: "__add", params: []string{"float64", "float64"}, result: "float64"},
	{receiver: "float64", name: "__sub", params: []string{"float64", "float64"}, result: "float64"},
	{receiver: "float64", name: "__mul", params: []string{"float64", "float64"}, result: "float64"},
	{receiver: "float64", name: "__div", params: []string{"float64", "float64"}, result: "float64"},
	{receiver: "float64", name: "__mod", params: []string{"float64", "float64"}, result: "float64"},
	{receiver: "float64", name: "__lt", params: []string{"float64", "float64"}, result: "bool"},
	{receiver: "float64", name: "__le", params: []string{"float64", "float64"}, result: "bool"},
	{receiver: "float64", name: "__eq", params: []string{"float64", "float64"}, result: "bool"},
	{receiver: "float64", name: "__ne", params: []string{"float64", "float64"}, result: "bool"},
	{receiver: "float64", name: "__ge", params: []string{"float64", "float64"}, result: "bool"},
	{receiver: "float64", name: "__gt", params: []string{"float64", "float64"}, result: "bool"},
	{receiver: "float64", name: "__pos", params: []string{"float64"}, result: "float64"},
	{receiver: "float64", name: "__neg", params: []string{"float64"}, result: "float64"},
	{receiver: "float64", name: "__abs", params: []string{"float64"}, result: "float64"},
	{receiver: "float64", name: "__to", params: []string{"float64", "float"}, result: "float"},
	{receiver: "float64", name: "__to", params: []string{"float64", "float16"}, result: "float16"},
	{receiver: "float64", name: "__to", params: []string{"float64", "float32"}, result: "float32"},

	{receiver: "float", name: "__add", params: []string{"float", "float"}, result: "float"},
	{receiver: "float", name: "__sub", params: []string{"float", "float"}, result: "float"},
	{receiver: "float", name: "__mul", params: []string{"float", "float"}, result: "float"},
	{receiver: "float", name: "__div", params: []string{"float", "float"}, result: "float"},
	{receiver: "float", name: "__mod", params: []string{"float", "float"}, result: "float"},
	{receiver: "float", name: "__lt", params: []string{"float", "float"}, result: "bool"},
	{receiver: "float", name: "__le", params: []string{"float", "float"}, result: "bool"},
	{receiver: "float", name: "__eq", params: []string{"float", "float"}, result: "bool"},
	{receiver: "float", name: "__ne", params: []string{"float", "float"}, result: "bool"},
	{receiver: "float", name: "__ge", params: []string{"float", "float"}, result: "bool"},
	{receiver: "float", name: "__gt", params: []string{"float", "float"}, result: "bool"},
	{receiver: "float", name: "__pos", params: []string{"float"}, result: "float"},
	{receiver: "float", name: "__neg", params: []string{"float"}, result: "float"},
	{receiver: "float", name: "__abs", params: []string{"float"}, result: "float"},
	{receiver: "float", name: "__to", params: []string{"float", "string"}, result: "string"},
	{receiver: "float", name: "__to", params: []string{"float", "int"}, result: "int"},
	{receiver: "float", name: "__to", params: []string{"float", "uint"}, result: "uint"},
	{receiver: "float", name: "__to", params: []string{"float", "int8"}, result: "int8"},
	{receiver: "float", name: "__to", params: []string{"float", "int16"}, result: "int16"},
	{receiver: "float", name: "__to", params: []string{"float", "int32"}, result: "int32"},
	{receiver: "float", name: "__to", params: []string{"float", "int64"}, result: "int64"},
	{receiver: "float", name: "__to", params: []string{"float", "uint8"}, result: "uint8"},
	{receiver: "float", name: "__to", params: []string{"float", "uint16"}, result: "uint16"},
	{receiver: "float", name: "__to", params: []string{"float", "uint32"}, result: "uint32"},
	{receiver: "float", name: "__to", params: []string{"float", "uint64"}, result: "uint64"},
	{receiver: "float", name: "__to", params: []string{"float", "float16"}, result: "float16"},
	{receiver: "float", name: "__to", params: []string{"float", "float32"}, result: "float32"},
	{receiver: "float", name: "__to", params: []string{"float", "float64"}, result: "float64"},

	{receiver: "string", name: "__add", params: []string{"string", "string"}, result: "string"},
	{receiver: "string", name: "__mul", params: []string{"string", "int"}, result: "string"},
	{receiver: "string", name: "__eq", params: []string{"string", "string"}, result: "bool"},
	{receiver: "string", name: "__ne", params: []string{"string", "string"}, result: "bool"},
	{receiver: "string", name: "__to", params: []string{"string", "int"}, result: "int"},
	{receiver: "string", name: "__to", params: []string{"string", "uint"}, result: "uint"},
	{receiver: "string", name: "__to", params: []string{"string", "float"}, result: "float"},

	{receiver: "bool", name: "__eq", params: []string{"bool", "bool"}, result: "bool"},
	{receiver: "bool", name: "__ne", params: []string{"bool", "bool"}, result: "bool"},
	{receiver: "bool", name: "__not", params: []string{"bool"}, result: "bool"},
	{receiver: "bool", name: "__to", params: []string{"bool", "string"}, result: "string"},
	{receiver: "bool", name: "__to", params: []string{"bool", "int"}, result: "int"},
}

func (tc *typeChecker) ensureBuiltinMagic() {
	for _, spec := range builtinMagic {
		if spec.receiver == "" || spec.name == "" {
			continue
		}
		recv := symbols.TypeKey(spec.receiver)
		if tc.hasMagicSignature(recv, spec.name, spec.params, spec.result) {
			continue
		}
		sig := &symbols.FunctionSignature{
			Params:     make([]symbols.TypeKey, len(spec.params)),
			ParamNames: make([]source.StringID, len(spec.params)),
			Variadic:   make([]bool, len(spec.params)),
			Defaults:   make([]bool, len(spec.params)),
			Result:     symbols.TypeKey(spec.result),
		}
		for i, param := range spec.params {
			sig.Params[i] = symbols.TypeKey(param)
		}
		tc.addMagicEntry(recv, spec.name, sig)
	}
}

func (tc *typeChecker) hasMagicSignature(receiver symbols.TypeKey, name string, params []string, result string) bool {
	methods := tc.lookupMagicMethods(receiver, name)
	for _, sig := range methods {
		if sig == nil || len(sig.Params) != len(params) {
			continue
		}
		if string(sig.Result) != result {
			continue
		}
		match := true
		for i, param := range params {
			if string(sig.Params[i]) != param {
				match = false
				break
			}
		}
		if match {
			return true
		}
	}
	return false
}
