package abimanifest

import (
	"fmt"
	"go/format"
	"strings"
)

func renderGoView(view *SchemaView) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by abi-manifest-gen; DO NOT EDIT.\n\n")
	out.WriteString("package abimanifest\n\n")
	fmt.Fprintf(&out, "const GeneratedManifestHash = %q\n", view.Hash)
	fmt.Fprintf(&out, "const GeneratedSentinelSymbol = %q\n\n", view.Sentinel)
	out.WriteString("var GeneratedSchema = ")
	writeSchemaView(&out, "", view)
	out.WriteString("\n")
	return formatGeneratedGo(out.String())
}

func renderVMView(view *SchemaView) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by abi-manifest-gen; DO NOT EDIT.\n\n")
	out.WriteString("package vm\n\n")
	out.WriteString("import \"surge/internal/abimanifest\"\n\n")
	out.WriteString("var typedCarrierABISchema = ")
	writeSchemaView(&out, "abimanifest.", view)
	out.WriteString("\n")
	return formatGeneratedGo(out.String())
}

func writeSchemaView(out *strings.Builder, prefix string, view *SchemaView) {
	fmt.Fprintf(out, "%sSchemaView{Hash: %q, Sentinel: %q, ", prefix, view.Hash, view.Sentinel)
	fmt.Fprintf(out, "Enums: []%sEnumView{", prefix)
	for _, enum := range view.Enums {
		fmt.Fprintf(out, "{Name: %q, Underlying: %q, Semantics: %q, Values: []%sNamedValueView{", enum.Name, enum.Underlying, enum.Semantics, prefix)
		for _, value := range enum.Values {
			fmt.Fprintf(out, "{Name: %q, Value: %d, Semantics: %q},", value.Name, value.Value, value.Semantics)
		}
		out.WriteString("}},")
	}
	fmt.Fprintf(out, "}, Records: []%sRecordView{", prefix)
	for _, record := range view.Records {
		fmt.Fprintf(out, "{Name: %q, Role: %q, Semantics: %q, Fields: []%sFieldView{", record.Name, record.Role, record.Semantics, prefix)
		for _, field := range record.Fields {
			fmt.Fprintf(out, "{Name: %q, Type: %q, Semantics: %q},", field.Name, field.Type, field.Semantics)
		}
		out.WriteString("}},")
	}
	fmt.Fprintf(out, "}, Functions: []%sFunctionView{", prefix)
	for index := range view.Functions {
		function := &view.Functions[index]
		fmt.Fprintf(out, "{Name: %q, Semantics: %q, Result: %sResultView{Type: %q, Ownership: %q, Attributes: ", function.Name, function.Semantics, prefix, function.Result.Type, function.Result.Ownership)
		writeStringSlice(out, function.Result.Attributes)
		fmt.Fprintf(out, ", Semantics: %q}, Parameters: []%sParameterView{", function.Result.Semantics, prefix)
		for _, parameter := range function.Parameters {
			fmt.Fprintf(out, "{Name: %q, Type: %q, Ownership: %q, Attributes: ", parameter.Name, parameter.Type, parameter.Ownership)
			writeStringSlice(out, parameter.Attributes)
			fmt.Fprintf(out, ", Semantics: %q},", parameter.Semantics)
		}
		out.WriteString("}, Effects: ")
		writeStringSlice(out, function.Effects)
		out.WriteString("},")
	}
	out.WriteString("}}")
}

func writeStringSlice(out *strings.Builder, values []string) {
	out.WriteString("[]string{")
	for _, value := range values {
		fmt.Fprintf(out, "%q,", value)
	}
	out.WriteString("}")
}

func formatGeneratedGo(source string) ([]byte, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated Go ABI view: %w", err)
	}
	return formatted, nil
}
