package abimanifest

import (
	"fmt"
	"strings"
)

func renderLLVMView(manifest *Manifest, view *SchemaView) ([]byte, error) {
	enumWidths := make(map[string]string, len(manifest.Enums))
	for _, enum := range manifest.Enums {
		enumWidths[enum.Name] = enum.Underlying
	}
	var out strings.Builder
	out.WriteString("// Code generated by abi-manifest-gen; DO NOT EDIT.\n\n")
	out.WriteString("package llvm\n\n")
	out.WriteString("import \"surge/internal/abimanifest\"\n\n")
	fmt.Fprintf(&out, "const typedCarrierManifestHash = %q\n", view.Hash)
	fmt.Fprintf(&out, "const typedCarrierSentinelSymbol = %q\n\n", view.Sentinel)
	out.WriteString("type typedCarrierLLVMRecordDecl struct {\nname string\nfields []string\n}\n")
	out.WriteString("type typedCarrierLLVMParameterDecl struct {\nname string\nty string\nownership string\nattributes []string\nsemantics string\n}\n")
	out.WriteString("type typedCarrierLLVMFunctionDecl struct {\nname string\nresult string\nresultOwnership string\nresultAttributes []string\nresultSemantics string\nparameters []typedCarrierLLVMParameterDecl\neffects []string\nsemantics string\n}\n\n")
	out.WriteString("var typedCarrierLLVMRecords = []typedCarrierLLVMRecordDecl{")
	for _, record := range manifest.Records {
		fmt.Fprintf(&out, "{name: %q, fields: []string{", record.Name)
		for _, field := range record.Fields {
			fmt.Fprintf(&out, "%q,", llvmType(field.Type, enumWidths))
		}
		out.WriteString("}},")
	}
	out.WriteString("}\n\n")
	writeLLVMFunctions(&out, "typedCarrierLLVMCallbacks", manifest.Callbacks, enumWidths)
	writeLLVMFunctions(&out, "typedCarrierLLVMRuntimeFunctions", manifest.RuntimeFunctions, enumWidths)
	out.WriteString("var typedCarrierABISchema = ")
	writeSchemaView(&out, "abimanifest.", view)
	out.WriteString("\n")
	return formatGeneratedGo(out.String())
}

func writeLLVMFunctions(out *strings.Builder, name string, functions []Function, enumWidths map[string]string) {
	fmt.Fprintf(out, "var %s = []typedCarrierLLVMFunctionDecl{", name)
	for index := range functions {
		function := &functions[index]
		fmt.Fprintf(out, "{name: %q, result: %q, resultOwnership: %q, resultAttributes: ", function.Name, llvmType(function.Result.Type, enumWidths), function.Result.Ownership)
		writeStringSlice(out, function.Result.Attributes)
		fmt.Fprintf(out, ", resultSemantics: %q, parameters: []typedCarrierLLVMParameterDecl{", function.Result.Semantics)
		for _, parameter := range function.Parameters {
			fmt.Fprintf(out, "{name: %q, ty: %q, ownership: %q, attributes: ", parameter.Name, llvmType(parameter.Type, enumWidths), parameter.Ownership)
			writeStringSlice(out, parameter.Attributes)
			fmt.Fprintf(out, ", semantics: %q},", parameter.Semantics)
		}
		out.WriteString("}, effects: ")
		writeStringSlice(out, function.Effects)
		fmt.Fprintf(out, ", semantics: %q},", function.Semantics)
	}
	out.WriteString("}\n\n")
}

func llvmType(ref TypeRef, enumWidths map[string]string) string {
	switch ref.Kind {
	case "void":
		return "void"
	case "u8":
		return "i8"
	case "u32":
		return "i32"
	case "u64":
		return "i64"
	case "usize", "uintptr":
		return "intptr"
	case "pointer", "callback":
		return "ptr"
	case "named":
		if width, ok := enumWidths[ref.Name]; ok {
			return llvmType(TypeRef{Kind: width}, enumWidths)
		}
		return "%struct." + ref.Name
	default:
		panic("validated ABI type has no LLVM spelling: " + ref.Kind)
	}
}
