package abimanifest

import (
	"fmt"
	"strings"
)

func renderCHeader(manifest *Manifest, hash string) []byte {
	var out strings.Builder
	out.WriteString("// Code generated by abi-manifest-gen; DO NOT EDIT.\n")
	out.WriteString("// clang-format off\n")
	out.WriteString("#ifndef SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_GENERATED_H\n")
	out.WriteString("#define SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_GENERATED_H\n\n")
	out.WriteString("#include <stddef.h>\n#include <stdint.h>\n\n")
	out.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
	fmt.Fprintf(&out, "#define SURGE_TYPED_CARRIER_ABI_VERSION UINT32_C(%d)\n", manifest.Version)
	fmt.Fprintf(&out, "#define SURGE_TYPED_CARRIER_ABI_MANIFEST_HASH \"%s\"\n", hash)
	fmt.Fprintf(&out, "#define SURGE_TYPED_CARRIER_ABI_SENTINEL %s%s\n\n", manifest.SentinelPrefix, hash)

	for _, enum := range manifest.Enums {
		fmt.Fprintf(&out, "typedef %s %s;\n", cScalar(enum.Underlying), enum.Name)
		for _, value := range enum.Values {
			fmt.Fprintf(&out, "#define %s %s(%d)\n", value.Name, cConstantMacro(enum.Underlying), value.Value)
		}
		out.WriteString("\n")
	}
	for _, record := range manifest.Records {
		fmt.Fprintf(&out, "typedef struct %s %s;\n", record.Name, record.Name)
	}
	out.WriteString("\n")
	for index := range manifest.Callbacks {
		callback := &manifest.Callbacks[index]
		fmt.Fprintf(&out, "typedef %s (*%s)(", cType(callback.Result.Type), callback.Name)
		writeCParameterList(&out, callback.Parameters)
		out.WriteString(");\n")
	}
	out.WriteString("\n")
	for _, record := range manifest.Records {
		fmt.Fprintf(&out, "struct %s {\n", record.Name)
		for _, field := range record.Fields {
			fmt.Fprintf(&out, "    %s %s;\n", cType(field.Type), field.Name)
		}
		out.WriteString("};\n\n")
	}
	for index := range manifest.RuntimeFunctions {
		function := &manifest.RuntimeFunctions[index]
		fmt.Fprintf(&out, "%s %s(", cType(function.Result.Type), function.Name)
		writeCParameterList(&out, function.Parameters)
		out.WriteString(");\n")
	}
	fmt.Fprintf(&out, "extern const uint8_t rt_typed_carrier_abi_manifest_identity[];\n")
	out.WriteString("// NOLINTBEGIN(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)\n")
	out.WriteString("// The sentinel is deliberately in the reserved identifier space. It is the\n// implementation's own ABI marker, and a name a Surge program could also\n// define would prove nothing about which runtime got linked.\n")
	fmt.Fprintf(&out, "void %s%s(void);\n", manifest.SentinelPrefix, hash)
	out.WriteString("// NOLINTEND(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)\n\n")
	out.WriteString("#ifdef __cplusplus\n}\n#endif\n\n")
	out.WriteString("#endif\n// clang-format on\n")
	return []byte(out.String())
}

func renderCChecks(manifest *Manifest) []byte {
	var out strings.Builder
	out.WriteString("// Code generated by abi-manifest-gen; DO NOT EDIT.\n")
	out.WriteString("// clang-format off\n")
	out.WriteString("#ifndef SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_CHECKS_GENERATED_H\n")
	out.WriteString("#define SURGE_RUNTIME_NATIVE_RT_TYPED_CARRIER_ABI_CHECKS_GENERATED_H\n\n")
	out.WriteString("#include \"rt_typed_carrier_abi.generated.h\"\n\n")
	out.WriteString("#define SURGE_ABI_ALIGN_UP(value, align) (((value) + (align) - 1u) / (align) * (align))\n")
	out.WriteString("#define SURGE_ABI_MAX(left, right) ((left) > (right) ? (left) : (right))\n\n")
	for _, enum := range manifest.Enums {
		fmt.Fprintf(&out, "_Static_assert(sizeof(%s) == sizeof(%s), \"%s width drift\");\n", enum.Name, cScalar(enum.Underlying), enum.Name)
		for _, value := range enum.Values {
			fmt.Fprintf(&out, "_Static_assert(%s == %s(%d), \"%s value drift\");\n", value.Name, cConstantMacro(enum.Underlying), value.Value, value.Name)
		}
		out.WriteString("\n")
	}
	for _, record := range manifest.Records {
		writeCRecordChecks(&out, record)
	}
	out.WriteString("#if defined(__GNUC__) || defined(__clang__)\n")
	for index := range manifest.Callbacks {
		callback := &manifest.Callbacks[index]
		fmt.Fprintf(&out, "_Static_assert(__builtin_types_compatible_p(%s, %s (*)(", callback.Name, cType(callback.Result.Type))
		writeCParameterTypes(&out, callback.Parameters)
		fmt.Fprintf(&out, ")), \"%s signature drift\");\n", callback.Name)
	}
	for index := range manifest.RuntimeFunctions {
		function := &manifest.RuntimeFunctions[index]
		fmt.Fprintf(&out, "_Static_assert(__builtin_types_compatible_p(__typeof__(&%s), %s (*)(", function.Name, cType(function.Result.Type))
		writeCParameterTypes(&out, function.Parameters)
		fmt.Fprintf(&out, ")), \"%s signature drift\");\n", function.Name)
	}
	out.WriteString("#endif\n\n")
	out.WriteString("#undef SURGE_ABI_MAX\n#undef SURGE_ABI_ALIGN_UP\n\n#endif\n// clang-format on\n")
	return []byte(out.String())
}

func renderCSource(manifest *Manifest, hash string) []byte {
	var out strings.Builder
	out.WriteString("// Code generated by abi-manifest-gen; DO NOT EDIT.\n")
	out.WriteString("// clang-format off\n")
	out.WriteString("#include \"rt_typed_carrier_abi_checks.generated.h\"\n\n")
	out.WriteString("#if defined(__GNUC__) || defined(__clang__)\n")
	out.WriteString("#define SURGE_ABI_USED __attribute__((used))\n")
	out.WriteString("#define SURGE_ABI_NOINLINE __attribute__((noinline))\n")
	out.WriteString("#define SURGE_ABI_VISIBLE __attribute__((visibility(\"default\")))\n")
	out.WriteString("#else\n#define SURGE_ABI_USED\n#define SURGE_ABI_NOINLINE\n#define SURGE_ABI_VISIBLE\n#endif\n\n")
	out.WriteString("#if defined(__has_attribute)\n")
	out.WriteString("#if __has_attribute(retain)\n#define SURGE_ABI_RETAIN __attribute__((retain))\n#endif\n#endif\n")
	out.WriteString("#ifndef SURGE_ABI_RETAIN\n#define SURGE_ABI_RETAIN\n#endif\n\n")
	fmt.Fprintf(&out, "const uint8_t rt_typed_carrier_abi_manifest_identity[] = \"%s\";\n", hash)
	out.WriteString("\nconst uint8_t* rt_typed_carrier_abi_manifest_hash(void) {\n")
	out.WriteString("    return rt_typed_carrier_abi_manifest_identity;\n}\n\n")
	out.WriteString("static volatile uint8_t rt_typed_carrier_abi_retention_anchor;\n\n")
	out.WriteString("// NOLINTBEGIN(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)\n")
	fmt.Fprintf(&out, "SURGE_ABI_USED SURGE_ABI_RETAIN SURGE_ABI_NOINLINE SURGE_ABI_VISIBLE void %s%s(\n", manifest.SentinelPrefix, hash)
	out.WriteString("    void) {\n    (void)rt_typed_carrier_abi_retention_anchor;\n}\n")
	out.WriteString("// NOLINTEND(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)\n\n")
	out.WriteString("#undef SURGE_ABI_RETAIN\n#undef SURGE_ABI_VISIBLE\n#undef SURGE_ABI_NOINLINE\n#undef SURGE_ABI_USED\n")
	out.WriteString("// clang-format on\n")
	return []byte(out.String())
}

func writeCRecordChecks(out *strings.Builder, record Record) {
	// A field whose type is a pointer-to-aggregate makes clang-tidy read
	// `sizeof(((T*)0)->field)` as the sizeof-a-pointer mistake. Here the two
	// sides are deliberately both pointer sizes: the assert exists to catch the
	// field's type DRIFTING away from the ABI's, which is the one comparison
	// that has to be written this way.
	out.WriteString("// NOLINTBEGIN(bugprone-sizeof-expression)\n")
	defer out.WriteString("// NOLINTEND(bugprone-sizeof-expression)\n")
	maxAlign := "1u"
	for index, field := range record.Fields {
		fieldType := cType(field.Type)
		fmt.Fprintf(out, "_Static_assert(sizeof(((%s*)0)->%s) == sizeof(%s), \"%s.%s type drift\");\n", record.Name, field.Name, fieldType, record.Name, field.Name)
		if index == 0 {
			fmt.Fprintf(out, "_Static_assert(offsetof(%s, %s) == 0u, \"%s.%s offset drift\");\n", record.Name, field.Name, record.Name, field.Name)
		} else {
			previous := record.Fields[index-1]
			fmt.Fprintf(out, "_Static_assert(offsetof(%s, %s) == SURGE_ABI_ALIGN_UP(offsetof(%s, %s) + sizeof(((%s*)0)->%s), _Alignof(%s)), \"%s.%s offset drift\");\n", record.Name, field.Name, record.Name, previous.Name, record.Name, previous.Name, fieldType, record.Name, field.Name)
		}
		maxAlign = fmt.Sprintf("SURGE_ABI_MAX(%s, _Alignof(%s))", maxAlign, fieldType)
	}
	last := record.Fields[len(record.Fields)-1]
	fmt.Fprintf(out, "_Static_assert(_Alignof(%s) == %s, \"%s alignment drift\");\n", record.Name, maxAlign, record.Name)
	fmt.Fprintf(out, "_Static_assert(sizeof(%s) == SURGE_ABI_ALIGN_UP(offsetof(%s, %s) + sizeof(((%s*)0)->%s), _Alignof(%s)), \"%s size drift\");\n\n", record.Name, record.Name, last.Name, record.Name, last.Name, record.Name, record.Name)
}

func writeCParameterList(out *strings.Builder, parameters []Parameter) {
	if len(parameters) == 0 {
		out.WriteString("void")
		return
	}
	for index, parameter := range parameters {
		if index > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "%s %s", cType(parameter.Type), parameter.Name)
	}
}

func writeCParameterTypes(out *strings.Builder, parameters []Parameter) {
	if len(parameters) == 0 {
		out.WriteString("void")
		return
	}
	for index, parameter := range parameters {
		if index > 0 {
			out.WriteString(", ")
		}
		out.WriteString(cType(parameter.Type))
	}
}

func cType(ref TypeRef) string {
	switch ref.Kind {
	case "void", "u8", "u32", "u64", "usize", "uintptr":
		return cScalar(ref.Kind)
	case "named", "callback":
		return ref.Name
	case "pointer":
		base := ref.Name
		switch ref.Name {
		case "void":
			base = "void"
		case "u8":
			base = "uint8_t"
		}
		if ref.Const != nil && *ref.Const {
			base = "const " + base
		}
		return base + "*"
	default:
		panic("validated ABI type has no C spelling: " + ref.Kind)
	}
}

func cScalar(kind string) string {
	switch kind {
	case "void":
		return "void"
	case "u8":
		return "uint8_t"
	case "u32":
		return "uint32_t"
	case "u64":
		return "uint64_t"
	case "usize":
		return "size_t"
	case "uintptr":
		return "uintptr_t"
	default:
		panic("validated ABI scalar has no C spelling: " + kind)
	}
}

func cConstantMacro(kind string) string {
	switch kind {
	case "u8":
		return "UINT8_C"
	case "u32":
		return "UINT32_C"
	case "u64":
		return "UINT64_C"
	default:
		panic("validated ABI integer has no constant macro: " + kind)
	}
}
