// Package llvm implements the LLVM IR backend.
package llvm

type builtinDecl struct {
	name   string
	ret    string
	params []string
}

func runtimeDecls() []builtinDecl {
	return []builtinDecl{
		{name: "rt_alloc", ret: "ptr", params: []string{"i64", "i64"}},
		{name: "rt_free", ret: "void", params: []string{"ptr", "i64", "i64"}},
		{name: "rt_realloc", ret: "ptr", params: []string{"ptr", "i64", "i64", "i64"}},
		{name: "rt_memcpy", ret: "void", params: []string{"ptr", "ptr", "i64"}},
		{name: "rt_memmove", ret: "void", params: []string{"ptr", "ptr", "i64"}},
		{name: "rt_write_stdout", ret: "i64", params: []string{"ptr", "i64"}},
		{name: "rt_write_stderr", ret: "i64", params: []string{"ptr", "i64"}},
		{name: "rt_readline", ret: "ptr", params: nil},
		{name: "rt_argv", ret: "ptr", params: nil},
		{name: "rt_stdin_read_all", ret: "ptr", params: nil},
		{name: "rt_fs_cwd", ret: "ptr", params: nil},
		{name: "rt_fs_metadata", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_read_dir", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_mkdir", ret: "ptr", params: []string{"ptr", "i1"}},
		{name: "rt_fs_remove_file", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_remove_dir", ret: "ptr", params: []string{"ptr", "i1"}},
		{name: "rt_fs_open", ret: "ptr", params: []string{"ptr", "i32"}},
		{name: "rt_fs_close", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_read", ret: "ptr", params: []string{"ptr", "ptr", "i64"}},
		{name: "rt_fs_write", ret: "ptr", params: []string{"ptr", "ptr", "i64"}},
		{name: "rt_fs_seek", ret: "ptr", params: []string{"ptr", "i64", "i64"}},
		{name: "rt_fs_flush", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_read_file", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_write_file", ret: "ptr", params: []string{"ptr", "ptr", "i64", "i32"}},
		{name: "rt_fs_file_name", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_file_type", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_fs_file_metadata", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_net_listen", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_net_close_listener", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_net_close_conn", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_net_accept", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_net_read", ret: "ptr", params: []string{"ptr", "ptr", "i64"}},
		{name: "rt_net_write", ret: "ptr", params: []string{"ptr", "ptr", "i64"}},
		{name: "rt_net_wait_accept", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_net_wait_readable", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_net_wait_writable", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_exit", ret: "void", params: []string{"i64"}},
		{name: "rt_panic", ret: "void", params: []string{"ptr", "i64"}},
		{name: "rt_panic_numeric", ret: "void", params: []string{"ptr", "i64"}},
		{name: "rt_panic_bounds", ret: "void", params: []string{"i64", "i64", "i64"}},
		{name: "rt_string_from_bytes", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_string_from_utf16", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_string_ptr", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_string_len", ret: "i64", params: []string{"ptr"}},
		{name: "rt_string_len_bytes", ret: "i64", params: []string{"ptr"}},
		{name: "rt_string_index", ret: "i32", params: []string{"ptr", "i64"}},
		{name: "rt_string_slice", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_string_concat", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_string_repeat", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_string_eq", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_string_bytes_view", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_string_from_int", ret: "ptr", params: []string{"i64"}},
		{name: "rt_string_from_uint", ret: "ptr", params: []string{"i64"}},
		{name: "rt_string_from_float", ret: "ptr", params: []string{"double"}},
		{name: "rt_string_from_bigint", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_string_from_biguint", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_string_from_bigfloat", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_parse_int", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_parse_uint", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_parse_float", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_parse_bool", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_parse_bigint", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_parse_biguint", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_parse_bigfloat", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_from_literal", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_biguint_from_literal", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_bigfloat_from_literal", ret: "ptr", params: []string{"ptr", "i64"}},
		{name: "rt_bigint_from_i64", ret: "ptr", params: []string{"i64"}},
		{name: "rt_bigint_from_u64", ret: "ptr", params: []string{"i64"}},
		{name: "rt_biguint_from_u64", ret: "ptr", params: []string{"i64"}},
		{name: "rt_bigfloat_from_i64", ret: "ptr", params: []string{"i64"}},
		{name: "rt_bigfloat_from_u64", ret: "ptr", params: []string{"i64"}},
		{name: "rt_bigfloat_from_f64", ret: "ptr", params: []string{"double"}},
		{name: "rt_bigint_to_i64", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_to_u64", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_to_f64", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_add", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_sub", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_mul", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_div", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_mod", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_neg", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigint_abs", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigint_cmp", ret: "i32", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_bit_and", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_bit_or", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_bit_xor", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_shl", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_shr", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_add", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_sub", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_mul", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_div", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_mod", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_cmp", ret: "i32", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_bit_and", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_bit_or", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_bit_xor", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_shl", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_biguint_shr", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_add", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_sub", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_mul", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_div", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_mod", ret: "ptr", params: []string{"ptr", "ptr"}},
		{name: "rt_bigfloat_neg", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigfloat_abs", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigfloat_cmp", ret: "i32", params: []string{"ptr", "ptr"}},
		{name: "rt_bigint_to_biguint", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_biguint_to_bigint", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigint_to_bigfloat", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_biguint_to_bigfloat", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigfloat_to_bigint", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_bigfloat_to_biguint", ret: "ptr", params: []string{"ptr"}},
		{name: "__task_create", ret: "ptr", params: []string{"i64", "ptr"}},
		{name: "__task_state", ret: "ptr", params: nil},
		{name: "rt_task_wake", ret: "void", params: []string{"ptr"}},
		{name: "rt_task_poll", ret: "i8", params: []string{"ptr", "ptr"}},
		{name: "rt_task_await", ret: "void", params: []string{"ptr", "ptr", "ptr"}},
		{name: "rt_task_cancel", ret: "void", params: []string{"ptr"}},
		{name: "rt_task_clone", ret: "ptr", params: []string{"ptr"}},
		{name: "rt_timeout_poll", ret: "i8", params: []string{"ptr", "i64", "ptr"}},
		{name: "rt_select_poll_tasks", ret: "i64", params: []string{"i64", "ptr", "i64"}},
		{name: "rt_async_yield", ret: "void", params: []string{"ptr"}},
		{name: "rt_async_return", ret: "void", params: []string{"ptr", "i64"}},
		{name: "rt_async_return_cancelled", ret: "void", params: []string{"ptr"}},
		{name: "rt_channel_new", ret: "ptr", params: []string{"i64"}},
		{name: "rt_channel_send", ret: "i1", params: []string{"ptr", "i64"}},
		{name: "rt_channel_recv", ret: "i8", params: []string{"ptr", "ptr"}},
		{name: "rt_channel_try_send", ret: "i1", params: []string{"ptr", "i64"}},
		{name: "rt_channel_try_recv", ret: "i1", params: []string{"ptr", "ptr"}},
		{name: "rt_channel_close", ret: "void", params: []string{"ptr"}},
		{name: "rt_scope_enter", ret: "ptr", params: []string{"i1"}},
		{name: "rt_scope_register_child", ret: "void", params: []string{"ptr", "ptr"}},
		{name: "rt_scope_cancel_all", ret: "void", params: []string{"ptr"}},
		{name: "rt_scope_join_all", ret: "i1", params: []string{"ptr", "ptr", "ptr"}},
		{name: "rt_scope_exit", ret: "void", params: []string{"ptr"}},
		{name: "checkpoint", ret: "ptr", params: nil},
		{name: "rt_sleep", ret: "ptr", params: []string{"i64"}},
		{name: "rt_range_int_new", ret: "ptr", params: []string{"ptr", "ptr", "i1"}},
		{name: "rt_range_int_from_start", ret: "ptr", params: []string{"ptr", "i1"}},
		{name: "rt_range_int_to_end", ret: "ptr", params: []string{"ptr", "i1"}},
		{name: "rt_range_int_full", ret: "ptr", params: []string{"i1"}},
	}
}

func runtimeSigMap() map[string]funcSig {
	decls := runtimeDecls()
	m := make(map[string]funcSig, len(decls))
	for _, d := range decls {
		m[d.name] = funcSig{ret: d.ret, params: d.params}
	}
	return m
}
