// Code generated by "stringer -type=TriviaKind -trimprefix=Trivia"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TriviaSpace-0]
	_ = x[TriviaNewline-1]
	_ = x[TriviaLineComment-2]
	_ = x[TriviaBlockComment-3]
	_ = x[TriviaDocLine-4]
	_ = x[TriviaDocBlock-5]
	_ = x[TriviaDirective-6]
}

const _TriviaKind_name = "SpaceNewlineLineCommentBlockCommentDocLineDocBlockDirective"

var _TriviaKind_index = [...]uint8{0, 5, 12, 23, 35, 42, 50, 59}

func (i TriviaKind) String() string {
	if i >= TriviaKind(len(_TriviaKind_index)-1) {
		return "TriviaKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TriviaKind_name[_TriviaKind_index[i]:_TriviaKind_index[i+1]]
}
